apiVersion: v1
kind: Service
metadata:
  name: voting-app-svc
  namespace: voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
  ports:
  - port: 80
    targetPort: 80
    # NodePort será alocado automaticamente