apiVersion: batch/v1
kind: CronJob
metadata:
  name: ada-cronjob
spec:
  schedule: "*/1 * * * *" #Executa a cada 1 minuto
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: busybox
            command:
            - /bin/sh
            - -c
            - echo "hello cronjob"
          restartPolicy: OnFailure
